baseURL = "https://www.joseenriqueruiznavarro.com/"
languageCode = "en-us"
title = "Jose Enrique"
theme = "hugo-coder" 

languagecode = "en" 

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Jose Enrique Ruiz Navarro"
    description = "Jose Enrique's personal website"
    keywords = "blog,developer,personal"
    info = "DevOps and a little bit of all" 
    avatarurl = "https://avatars3.githubusercontent.com/u/1654589?s=460&v=4"
    footercontent = "Enjoy and get your dreams."

    hideCredits = true
    hideCopyright = false

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/joseEnrique"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/quiqueruizna"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/joseenriqueruiz/"


[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 5
    url = "/contact/"
